# Generated by Django 2.2.3 on 2019-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_of_origin',
            field=models.TextField(default='earth'),
            preserve_default=False,
        ),
    ]
