# Generated by Django 2.2.3 on 2019-07-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20190721_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviated_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='chat_app.Language'),
            preserve_default=False,
        ),
    ]
