# Generated by Django 2.2.3 on 2019-07-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='label',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
