dist: xenial
language: python
services:
- postgresql
- redis-server
python:
- 3.7
env:
- DJANGO=2.2 DB=postgres
before_install:
- export DJANGO_SETTINGS_MODULE=LangChat.settings.test
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: DUjt4kWr2vYEtJfVQyzAFhElYKnJ0zCssUFYo+/EvZiZ3BO95aEz06QE+r3jSwjrkSVfiYwiRJ64kB9l8NJZ4Z+8Sd59jjUE/EAfSPDU9IhAjGTvkGo4HUTJbRIeN5Www4q52Rab3QUKjvKNZP5QyQ027DNGVZyOMwaxVnkq0P4rbY7oGY/A/TLE2o70dvN8gVYVYqCae2yhCFa5PwwntAfOyq/3hgdHbWusdxJmNeqlIIFmstCaFHfAkDxWgZH74vVDj9VUOIXk2F0/1pT+F8CK4fK/0wjkWfZwQfMU5XgIo6pA1KLYuzizq7yyXFK6KtCjxZr34Kt0vY+12X3Pj1kC37JcSDCNT1Lit+n+gBFuzST0jbCGoqNvM0fI1DpeS0sGY+Hv9FlCS3lcWKR1hGLxkpidrUtiippjD2cLnmLcU7lGrCQwwbs0ZR/pRWe74oz/Vw90a8CARCoOrpo10GhrjEC3DeG8KwAMgLnbGI0bI570tJK5go3LbIis8MpUHSdnn1EeVVAvRxXnbu7mnKAKsY8A2zAFJjJBXAzYGYG/P687IGrFp+sDMRqpoSqUaVj4thPv6yoyW1hcuKxUNMWZIR3ZoR3eRJkzWZszPjNdNRWdAo9PsOx8w2DSrdlB1fjaZ/2JkGMhB7QZ7/30Ca07EARL4Bx8jtV2MPosw6c=
  app: langchat-crosspollination
  on:
    repo: blake-enyart/LangChat_django
