dist: xenial
language: python
services:
- postgresql
python:
- 3.7
env:
- DJANGO=2.2 DB=postgres
- export DJANGO_SETTINGS_MODULE=django_postgres_example.settings.travis
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE testing_db;" -U postgres
- psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: rhtOmuEKeH/+HWic1RWbga6wE7su0wbmjjPPiwP2g03xH5CPMt69yYf7UCzR3fJwf0dNsbUdhbvo6mo79Y6mOHc/S3jvIjU3mMmx6SmIdTlyeNX3/5tk6Pnl8hHAce+hPO2LRvdcq96snkYhDI1ZHZEa/8ySRXtylP0Y5SODsfbPjsM99nvbdPDn7ioSf5p0fOQuT6HT5JwTN7nEgs85F6aiNLvUyjmNmUqh7XfNhtUqAqLbYBA2AAOL+6m5N9LVwkQk3kccDP5gzJ0UGxUvGArqja5s8XfoepIifp0J/KEkJuumoQVY8gPDMfh83neZSkt9GegppIWbV9SGN+63Rz7ZY9XGMd9pwS7Etk+Y1LhxXrjvJp7HXzeObnIuhEeRN+ncQMSCgRq3AbB/5d2IfDd+T4Jz36MAD8HVavhypq6xfrTVF1BXYIQ2Gaz23JQYd527oiT+qRwd2LxG7V0G0PhJOMSeoltJQN3lVECsg4njhhXuzHK7KX350DNxp+6XCZlMGUZmqBXpiCVgPvLM9lVr+6aqW+XoHaiNfcPKhzSEujNcz1G5MaKi9Du7zXybrbNGAnMBjbHl9sUwLq8YDfQixO5RuRgfoOjAwftPs8hBvB+/kI2NgcD3SYFVFmP17kt2br7FUmZdwheDuRc/ua2tkcLzXfXbtomDlJqfY3c=
  app: langchat-crosspollination
  on:
    repo: blake-enyart/LangChat_django
