dist: xenial
language: python
services:
- postgresql
python:
- 3.7
env:
- DJANGO=2.2 DB=postgres
- export DJANGO_SETTINGS_MODULE=django_postgres_example.settings.travis
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE testing_db;" -U postgres
- psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: qRrM2atFGHmsSsd4AwTC6bOXrvbO4fNWaGsjOdUY4Z12wgqIMmFst/YCMFLM7LgF5czEA6JnvR0/IavPqCyMLRZa5S6DApKo6UBwQ/aFisnPWCOnOPPcR18OiV00S1MGpEBWY7d/LALSmzRz8DVwylQ4qyWEqMzfSmIbzyj3V71uyZp3R5cKF8wxOF6xZBbGTsMMk6Wxsq/84v9Fc3sz9JUo/oKMG5Py/G+qryYSIMuevCeoH5ooRiGV/U72TlXKyZCIwMR2BZs3UTmzakxGxQEcl+WBF5bfZ5CbQt6hyqjRb2j8Rcz0fm6v64u+OXwzi/YMHbWLyzn6j5KoJyL2Lc9sJC3mCl2lv900ChIwFpFmKWC7kKfZd9EPTEldSs1jlHbjZbnWWv8EvSNJdaZHc+i6ykgaMx2gfY3LBeXBumPBeHcT6zK83rs7DWpnnb2/1tWyDQEx3GBEu60M1XknPj78bDUcRrjLB91D/8vzywGgIQ2yT4NB+shVtm/5Be9TTmY+SzKUgIS6hLrIVEBA3xuDLpwge5hvkbpB//zIx5JHrpautEL/Cfh22Qtj8Bzq9+yoBJMqIlKJagQLW5HgEBO3peoWPKOE3KBakEQ8Ihm3IPe069Dja6YfUvk62rrby81/2RGSGsFjOgD+Ffz5A58eVPqR8zgcE5Rsk6Rz/jI=
  app: langchat-crosspollination
  on:
    repo: blake-enyart/LangChat_django
